CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY
    , first_name VARCHAR(50) NOT NULL
    , last_name VARCHAR(50) NOT NULL
    , email VARCHAR(255) UNIQUE NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
)
;